name: Refraction Engine V1 - CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run nightly at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      parity_threshold:
        description: 'Parity threshold in arcseconds'
        required: false
        default: '90'
        type: string

jobs:
  # ==========================================================================
  # JOB 1: Guard Suite (Core Tests)
  # ==========================================================================
  guard-suite:
    name: Guard Suite (Specs & Schemas)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      
      - name: Run guard suite
        run: |
          chmod +x scripts/run_guard_suite.sh
          ./scripts/run_guard_suite.sh
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: guard-suite-results-${{ matrix.python-version }}
          path: |
            .pytest_cache/
            test-results/

  # ==========================================================================
  # JOB 2: Parity Suite (Accuracy Tests)
  # ==========================================================================
  parity-suite:
    name: Parity Suite (PL9 Accuracy)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: guard-suite  # Only run if guard suite passes
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      
      - name: Set parity threshold
        run: |
          if [ "${{ github.event.inputs.parity_threshold }}" != "" ]; then
            echo "PARITY_THRESHOLD=${{ github.event.inputs.parity_threshold }}" >> $GITHUB_ENV
          else
            echo "PARITY_THRESHOLD=90" >> $GITHUB_ENV
          fi
      
      - name: Run parity suite
        run: |
          chmod +x scripts/run_parity_suite.sh
          ./scripts/run_parity_suite.sh -v
      
      - name: Upload parity results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: parity-suite-results
          path: |
            .pytest_cache/
            test-results/
            parity-report.txt
      
      - name: Comment PR with parity results
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            let comment = '## 🎯 Parity Suite Results\n\n';
            
            if (fs.existsSync('parity-report.txt')) {
              const report = fs.readFileSync('parity-report.txt', 'utf8');
              comment += '```\n' + report + '\n```\n';
            } else {
              comment += '✅ All parity tests passed!\n';
              comment += `Threshold: ${process.env.PARITY_THRESHOLD} arcseconds\n`;
            }
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

  # ==========================================================================
  # JOB 3: Code Quality Checks
  # ==========================================================================
  code-quality:
    name: Code Quality (Lint & Format)
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 mypy
      
      - name: Check formatting (black)
        run: |
          black --check src/ tests/
      
      - name: Check linting (flake8)
        run: |
          flake8 src/ tests/ --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 src/ tests/ --count --max-complexity=10 --max-line-length=127 --statistics
      
      - name: Check types (mypy)
        run: |
          mypy src/refraction_engine/ --ignore-missing-imports
        continue-on-error: true  # Don't fail CI on type errors yet

  # ==========================================================================
  # JOB 4: Bundle Generation & Validation
  # ==========================================================================
  bundle-validation:
    name: Bundle Generation & Schema Validation
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: guard-suite
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install jsonschema
      
      - name: Generate bundles
        run: |
          python -m refraction_engine.cli mehran_birth.json > mehran_bundle.json
          python -m refraction_engine.cli athena_birth.json > athena_bundle.json
          python -m refraction_engine.cli arezoo_birth.json > arezoo_bundle.json
          python -m refraction_engine.cli arman_birth.json > arman_bundle.json
      
      - name: Validate against schema
        run: |
          python scripts/validate_bundle_schema.py mehran_bundle.json
          python scripts/validate_bundle_schema.py athena_bundle.json
          python scripts/validate_bundle_schema.py arezoo_bundle.json
          python scripts/validate_bundle_schema.py arman_bundle.json
      
      - name: Upload generated bundles
        uses: actions/upload-artifact@v3
        with:
          name: generated-bundles
          path: |
            *_bundle.json

  # ==========================================================================
  # JOB 5: Coverage Report
  # ==========================================================================
  coverage:
    name: Test Coverage Report
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: guard-suite
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install pytest-cov
      
      - name: Run tests with coverage
        run: |
          pytest tests/specs --cov=src/refraction_engine --cov-report=xml --cov-report=html
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
      
      - name: Upload coverage HTML report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: htmlcov/

  # ==========================================================================
  # FINAL: Status Check
  # ==========================================================================
  ci-status:
    name: CI Status
    runs-on: ubuntu-latest
    needs: [guard-suite, parity-suite, code-quality, bundle-validation, coverage]
    if: always()
    
    steps:
      - name: Check all jobs status
        run: |
          if [ "${{ needs.guard-suite.result }}" != "success" ]; then
            echo "❌ Guard suite failed"
            exit 1
          fi
          if [ "${{ needs.parity-suite.result }}" != "success" ]; then
            echo "❌ Parity suite failed"
            exit 1
          fi
          if [ "${{ needs.code-quality.result }}" != "success" ]; then
            echo "⚠️  Code quality checks failed (non-blocking)"
          fi
          if [ "${{ needs.bundle-validation.result }}" != "success" ]; then
            echo "❌ Bundle validation failed"
            exit 1
          fi
          if [ "${{ needs.coverage.result }}" != "success" ]; then
            echo "⚠️  Coverage report failed (non-blocking)"
          fi
          
          echo "✅ All critical checks passed!"
          echo "🎉 CI pipeline successful!"
